### ISSUE TITLE
Add ability to not use coreSchema

### ISSUE THREAD

**Issue by carlrosell** [rexxars/sanity-graphql-schema#1]
Hi there!
Thx for a really nice repo. I would like it if there was an option not to use the core schema as I would like to provide it myself. The reason for that is that I'm using the schema for my graphql endpoint as well.

**Comment by rexxars** [comment]
Thanks! 
I'm not sure I understand what you mean, could you be a little clearer? Which core schema are you thinking of?

**Comment by carlrosell** [comment]
Sorry for being unclear, I was in the park with my kid when I wrote that 😄 
The problem I had was that I have one graphql schema that is used both from the server, and I was trying to use the same for generating the sanity schema. When I tried that I had colliding types for the types in the coreSchema.js file. So I thought we could add an option to skip adding them by default. I then forked the repo and tried to do it myself and then I noticed why they were there in the first place. Long story short, I solved this by having an extra step that removed the colliding types before passing the schema to fromGQL.
