### ISSUE TITLE
Add preview object to schema

### ISSUE THREAD

**Issue by presto2116** [rexxars/sanity-graphql-schema#2]
I have been playing around with sanity and since our team is heavily reliant on graphql schema we would like to incorporate it in our sanity schema. The transition has been easy enough for most of our components. but seems to fail when we have a custom preview object that renders either text or a custom React component. I have a simple example below

Using grapql
```
export default graphql`
  type Button implements Document {
    url: Url!
    text: String!
  }
`;
```

Old version
```
const ButtonPreview = ({ value }) => (
  <StyledBtn>
    {value.text}
  </StyledBtn>
);

export default {
  title: 'Button',
  name: 'button',
  type: 'document',
  fields: [
    {
      title: 'URL',
      name: 'url',
      type: 'url'
    },
    {
      title: 'Text',
      name: 'text',
      type: 'string'
    }
  ],
  preview: {
    select: {
      text: 'text'
    },
    component: ButtonPreview
  }
};
```

Is there a current way to implement a custom preview or is it an issue currently being worked on? Thanks again for this awesome plugin. helps with using a lot of our previous graphql schema

**Comment by rexxars** [comment]
Thanks for the kind words! This is very much a side project, so I have not had time to give it too much attention lately.

My plan for all things like this is to implement some kind of "registry", maybe something like this:
```js
const graphqlSdl = graphql`
  type Button implements Document @preview(id: "button") {
    url: Url!
    text: String!
  }
`

export default createSchema({
  name: 'default',
  types: fromGQL(graphqlSdl, {
    previews: {
      button: {
        select: {text: 'text'},
        component: ButtonPreview
      }
    }
  })
})
```
